CREATE PROC GET_SINGLE_PRODUCT
@ID VARCHAR(30)
AS

SELECT [ID_PRODUCT]
      ,[LABEL_PRODUCT]
      ,[QTE_IN_SROCK]
      ,[PRICE]
      ,[IMAGE_PRODUCT]
      ,[DESCRIPTION_CAT] -- TO GET ONLY DESC OF CAT
  FROM [dbo].[PRODUCTS]
	INNER JOIN CATEGORIES
	ON CATEGORIES.ID_CAT = [PRODUCTS].ID_CAT
	WHERE PRODUCTS.ID_PRODUCT = @ID

