CREATE PROC UPDATE_PRODCUTS
@ID_CAT INT,
@ID_PRODUCT VARCHAR(30),
@LABEL NVARCHAR(MAX),
@Qte INT,
@PRICE VARCHAR(50),
@Img IMAGE
AS
UPDATE  PRODUCTS
SET ID_CAT = @ID_CAT,
LABEL_PRODUCT = @LABEL,
QTE_IN_SROCK = @Qte,
PRICE = @PRICE,
IMAGE_PRODUCT = @Img
WHERE ID_PRODUCT = @ID_PRODUCT