ALTER PROC SEARCH_PRODUCTS
@ID NVARCHAR(50)
AS

SELECT [ID_PRODUCT] as 'رقم المنتج'
      ,[LABEL_PRODUCT] as 'وصف المنتج'
      ,[QTE_IN_SROCK] as 'الكمية المخزنة'
      ,[PRICE] as 'سعر المنتج'
      ,[DESCRIPTION_CAT] as 'الصنف'
  FROM [dbo].[PRODUCTS]
	INNER JOIN CATEGORIES
	ON CATEGORIES.ID_CAT = [PRODUCTS].ID_CAT

	WHERE [ID_PRODUCT] + [LABEL_PRODUCT] + CONVERT(VARCHAR,[QTE_IN_SROCK]) + [PRICE] + [DESCRIPTION_CAT]
	LIKE '%' + @ID + '%'