CREATE PROC ADD_ORDER
@ID_ORDER INT,
@DATE_ORDER DATETIME,
@CUSTOMER_ID INT,
@DESCRIPTION_ORDER NVARCHAR(250),
@SALESMAN nVARCHAR(75)
AS

INSERT INTO [dbo].[ORDERS]
           ([ID_ORDER]
           ,[DATE_ORDER]
           ,[SALESMAN]
           ,[DESCRIPTION_ORDER]
           ,[CUSTOMER_ID])
     VALUES
           (@ID_ORDER
           ,@DATE_ORDER
		   ,@SALESMAN
		   ,@DESCRIPTION_ORDER
           ,@CUSTOMER_ID)

